---
- name: Remove existing config.toml
  become: true
  ansible.builtin.file:
    path: /etc/gitlab-runner/config.toml
    state: absent

- name: Register GitLab runner
  ansible.builtin.command: >
    /usr/bin/gitlab-runner register
    --non-interactive
    --url {{ register_runner_runner_register_url }}
    --token {{ register_runner_runner_authentication_token }}
    --executor {{ register_runner_runner_executor }}
    --docker-image {{ register_runner_runner_docker_image }}
    --docker-privileged
    --docker-volumes {{ register_runner_runner_docker_volumes }}
  become: true
  register: registration_output
  changed_when: true

- name: Verify GitLab Runner connection
  become: true
  ansible.builtin.command: gitlab-runner verify
  register: runner_verify
  changed_when: false

- name: Check for successful verification
  ansible.builtin.debug:
    msg: "GitLab runner verification: {{ runner_verify.stdout }}"
  failed_when: runner_verify.rc != 0
