---
- name: Install GitLab Runner repository
  become: true
  ansible.builtin.get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh"
    dest: "/tmp/script.deb.sh"
    mode: "0700"

- name: Set execute permission for installation script
  become: true
  ansible.builtin.file:
    path: "/tmp/script.deb.sh"
    mode: "u+x"

- name: Execute installation script
  become: true
  ansible.builtin.command: /tmp/script.deb.sh
  changed_when: false

- name: Install GitLab Runner
  become: true
  ansible.builtin.apt:
    name: gitlab-runner
    state: present

- name: Restart GitLab Runner service
  ansible.builtin.systemd:
    name: gitlab-runner
    state: restarted

- name: Ensure GitLab Runner service is running
  become: true
  ansible.builtin.service:
    name: gitlab-runner
    state: started
  register: gitlab_runner_status
